### ISSUE TITLE
Discussion: validator table relationships

### ISSUE THREAD

**Issue by ryuash** [forbole/soljuno#92]
Just opening up a discussion:
Currently there are no relationships between `validator_status` and `validator_config`. 
This will require me to query for things twice (which is fine if performance will be an issue) in the future but i'm not 100% about the performance. 

It's also a bit weird that we don't have a `validator` table.
Is there a reasoning for this design?

**Comment by dadamu** [comment]
@ryuash 
It is the naming issue. since solana calls validator account as vote account. Actually they can be the same, I think we should call it `validator` table instead of `vote_account`
