### ISSUE TITLE
Transactions Table missing timestamp and results

### ISSUE THREAD

**Issue by ryuash** [forbole/soljuno#95]
Would it be possible for me to get the result (boolean) and timestamp?
![image](https://user-images.githubusercontent.com/42913823/145350080-7d0eec81-53cf-4bff-a921-46b51d736792.png)

![image](https://user-images.githubusercontent.com/42913823/145350106-b80f8979-9814-4f23-a01e-2095af737d46.png)

**Comment by dadamu** [comment]
@ryuash Yeah, timestamp is in the block, the route is `tx -> block -> timestamp`. Result is `!error`.

**Comment by ryuash** [comment]
ok!
